nhentai:
  http4k:
    proxy-enabled: false
    proxy-host: 127.0.0.1
    proxy-port: 7890
  path:
    files: ./static/files
    galleries: ./static/galleries
    previews: ./static/previews
spring:
  datasource:
    url: jdbc:sqlite:file::memory:?cache=shared
  exposed:
    show-sql: true