spring:
  application:
    name: ncomic-springboot
  datasource:
    url: jdbc:sqlite:./data/ncomic.db
    driver-class-name: org.sqlite.JDBC
  exposed:
    generate-ddl: true
    show-sql: true
logging:
  file:
    path: ./logs/
