nhentai:
  http4k:
    proxy-enabled: false
    proxy-host: 127.0.0.1
    proxy-port: 7890
  path:
    files: ./static/files
    galleries: ./static/galleries
    previews: ./static/previews
spring:
  datasource:
    url: jdbc:sqlite:nhentai-dev.db?journal_mode=WAL&busy_timeout=5000
    driver-class-name: org.sqlite.JDBC
  exposed:
    show-sql: true
    generate-ddl: true